In [1]:
import pandas as pd
import datetime

create a varible with dates and from that extract the weekday

I create a list of dates with 20 days difference from today

and then tranform into a dataframe

In [7]:
df_base=datetime.datetime.today()
df_date_list = [df_base-datetime.timedelta(days=x) for x in range (0,20)]
df=pd.DataFrame(df_date_list)
df.columns=['day']
df

                          day
0  2021-06-02 09:35:16.246414
1  2021-06-01 09:35:16.246414
2  2021-05-31 09:35:16.246414
3  2021-05-30 09:35:16.246414
4  2021-05-29 09:35:16.246414
5  2021-05-28 09:35:16.246414
6  2021-05-27 09:35:16.246414
7  2021-05-26 09:35:16.246414
8  2021-05-25 09:35:16.246414
9  2021-05-24 09:35:16.246414
10 2021-05-23 09:35:16.246414
11 2021-05-22 09:35:16.246414
12 2021-05-21 09:35:16.246414
13 2021-05-20 09:35:16.246414
14 2021-05-19 09:35:16.246414
15 2021-05-18 09:35:16.246414
16 2021-05-17 09:35:16.246414
17 2021-05-16 09:35:16.246414
18 2021-05-15 09:35:16.246414
19 2021-05-14 09:35:16.246414

In [14]:
# extract the week day name
df['day_of_week']=df['day'].dt.day_name()
df.head()

                         day day_of_week
0 2021-06-02 09:35:16.246414   Wednesday
1 2021-06-01 09:35:16.246414     Tuesday
2 2021-05-31 09:35:16.246414      Monday
3 2021-05-30 09:35:16.246414      Sunday
4 2021-05-29 09:35:16.246414    Saturday

In [18]:
#enginner categorial variable by ordinal number replacement
weekday_map ={ 'Monday':1,
              'Tuesday':2,
              'Wednesday':3,
              'Thursday':4,
              'Friday':5,
              'Saturday':6,
              'Sunday':7      
}
df['day_ordinal']=df.day_of_week.map(weekday_map)
df.head(20)

                          day day_of_week  day_ordinal
0  2021-06-02 09:35:16.246414   Wednesday            3
1  2021-06-01 09:35:16.246414     Tuesday            2
2  2021-05-31 09:35:16.246414      Monday            1
3  2021-05-30 09:35:16.246414      Sunday            7
4  2021-05-29 09:35:16.246414    Saturday            6
5  2021-05-28 09:35:16.246414      Friday            5
6  2021-05-27 09:35:16.246414    Thursday            4
7  2021-05-26 09:35:16.246414   Wednesday            3
8  2021-05-25 09:35:16.246414     Tuesday            2
9  2021-05-24 09:35:16.246414      Monday            1
10 2021-05-23 09:35:16.246414      Sunday            7
11 2021-05-22 09:35:16.246414    Saturday            6
12 2021-05-21 09:35:16.246414      Friday            5
13 2021-05-20 09:35:16.246414    Thursday            4
14 2021-05-19 09:35:16.246414   Wednesday            3
15 2021-05-18 09:35:16.246414     Tuesday            2
16 2021-05-17 09:35:16.246414      Monday            1
17 2021-05-16 09:35:16.246414      Sunday            7
18 2021-05-15 09:35:16.246414    Saturday            6
19 2021-05-14 09:35:16.246414      Friday            5